import type { TCustomer } from "@modules/customers/types"
import type {
  TOrder,
  TOrderChannel,
  TOrderPaymentMethod,
  TOrderPaymentStatus,
  TOrderShippingCompany,
} from "./types"
import { TableColumn } from "@components/DataTable.vue"
import { getSmartDateLabel } from "@/utils/formatDate"
import { formatCurrency } from "@/utils/format-currency"

export const ORDERS: TOrder[] = [
  {
    id: 3197,
    order_ref: "30225082801251144",
    items_count: 1,
    total_amount: "5000.00",
    store: 225,
    customer: null,
    customer_info: null,
    shipping_price: "0.00",
    products_total: "5000.00",
    fulfilled: 0,
    unique_items: 1,
    paid_amount: "0.00",
    shipping_company: "0",
    rate: null,
    shipping_paid: false,
    shipping_mode: false,
    payment_status: 0,
    payment_mode: 1,
    channel: 3,
    refund: false,
    refund_amount: "0.00",
    issues_count: 0,
    cancelled: false,
    address: null,
    order_date: "2025-08-28T15:45:04.754797+01:00",
    items: [
      {
        id: 5635,
        has_feedback: false,
        index: 0,
        lead_time: 5,
        note: "",
        product: 1449,
        productid: 1449,
        sku: null,
        product_info: {
          id: 1449,
          product_name: "cap",
          product_type: "",
          description:
            "Our Castile Liquid Soap is a gentle, all-natural cleanser made from pure plant-based oils. Free from synthetic fragrances, parabens, and harsh chemicals, it’s perfect for everyday use on your hands, body, face, and even household cleaning.",
          price: 5000,
          total_stock: 100,
          has_variant: true,
          display: true,
          discount: "",
          discount_type: "0",
          has_discount: false,
          slug: "drew",
          store: "drew",
          temp_id: "",
          category: null,
          rating: "0.0",
          review_count: 0,
          rate_tracking: "0,0,0,0,0",
          strict_stock_count: true,
          created: "2025-08-15T02:07:29.543815+01:00",
          last_sale: "2025-08-28T16:45:04.781940+01:00",
          options1: "",
          options2: "",
          options3: "",
          variants: "",
          combinations: null,
          images: [],
          sku: [
            {
              id: 2116,
              sku: "4f7f73b9-bd0f-4bb0-b52a-3d33fa8eba3b",
              option1: "",
              option2: "",
              option3: "",
              has_discount: false,
              sku_discount: "",
              sku_discount_type: "0",
              price: 5000,
              qty: 100,
              event_data: {},
            },
          ],
          events: [
            {
              id: 88,
              event_ref: "ad83673777",
              event_name: "staging",
              start_date: "2025-08-15",
              end_date: "2026-01-01",
              created: "2025-08-15T02:08:25.349374+01:00",
            },
          ],
          display_event_data: {
            "88": {
              display_product: true,
            },
          },
          inventory_data: {
            "88": 100,
          },
          unit_weight: "2.000",
          length: "0.00",
          breadth: "0.00",
          height: "0.00",
        },
        var1name: "",
        var2name: "",
        selected_option1: "Pink",
        selected_option2: "Medium",
        qty: 1,
        delivered_qty: 0,
        price_sold: 5000,
        status: 1,
        sub_total: "5000",
        created: "2025-08-28T16:45:04.777819+01:00",
        modified: "2025-08-28T16:45:04.777837+01:00",
        selected_position: 1,
        is_returned: false,
        images: [],
      },
    ],
    event: 88,
    is_voided: false,
    void_reason: null,
    status: 0,
    shipping_provider: "manual",
    has_shipping: false,
  },
  {
    id: 3195,
    order_ref: "202250828012510700",
    items_count: 1,
    total_amount: "100.00",
    store: 225,
    customer: null,
    customer_info: null,
    shipping_price: "0.00",
    products_total: "100.00",
    fulfilled: 1,
    unique_items: 1,
    paid_amount: "100.00",
    shipping_company: "",
    rate: null,
    shipping_paid: false,
    shipping_mode: false,
    payment_status: 1,
    payment_mode: 0,
    channel: 0,
    refund: false,
    refund_amount: "0.00",
    issues_count: 0,
    cancelled: false,
    address: null,
    order_date: "2025-08-28T08:10:35.540854+01:00",
    items: [
      {
        id: 5633,
        has_feedback: false,
        index: 0,
        lead_time: null,
        note: "",
        product: 1460,
        productid: 1460,
        sku: null,
        product_info: {
          id: 1460,
          product_name: "shoo",
          product_type: "",
          description:
            "Our Castile Liquid Soap is a gentle, all-natural cleanser made from pure plant-based oils. Free from synthetic fragrances, parabens, and harsh chemicals, it’s perfect for everyday use on your hands, body, face, and even household cleaning.",
          price: 100,
          total_stock: 9,
          has_variant: true,
          display: true,
          discount: "",
          discount_type: "0",
          has_discount: false,
          slug: "drew",
          store: "drew",
          temp_id: "",
          category: null,
          rating: "0.0",
          review_count: 0,
          rate_tracking: "0,0,0,0,0",
          strict_stock_count: true,
          created: "2025-08-19T22:09:12.412121+01:00",
          last_sale: "2025-08-28T09:10:35.565916+01:00",
          options1: "",
          options2: "",
          options3: "",
          variants: "",
          combinations: null,
          images: [],
          sku: [
            {
              id: 2117,
              sku: "578646b5-1961-469a-990a-295285c6b7d0",
              option1: "",
              option2: "",
              option3: "",
              has_discount: false,
              sku_discount: "",
              sku_discount_type: "0",
              price: 100,
              qty: 9,
              event_data: {},
            },
          ],
          events: [
            {
              id: 94,
              event_ref: "22189d16aa",
              event_name: "reg",
              start_date: "2025-08-20",
              end_date: "2027-06-20",
              created: "2025-08-19T22:09:44.467675+01:00",
            },
          ],
          display_event_data: {
            "94": {
              display_product: true,
            },
          },
          inventory_data: {
            "94": 10,
          },
          unit_weight: "2.000",
          length: "0.00",
          breadth: "0.00",
          height: "0.00",
        },
        var1name: "",
        var2name: "",
        selected_option1: "",
        selected_option2: "",
        qty: 1,
        delivered_qty: 1,
        price_sold: 100,
        status: 1,
        sub_total: "0",
        created: "2025-08-28T09:10:35.562586+01:00",
        modified: "2025-08-28T09:10:35.562611+01:00",
        selected_position: 1,
        is_returned: false,
        images: [],
      },
    ],
    event: null,
    is_voided: false,
    void_reason: null,
    status: 1,
    shipping_provider: "manual",
    has_shipping: false,
  },
  {
    id: 3179,
    order_ref: "30225082101259772",
    items_count: 1,
    total_amount: "10000.00",
    store: 225,
    customer: 5234,
    customer_info: {
      id: 5234,
      uid: 5234,
      store: 225,
      first_name: "Daniel",
      last_name: "Obode",
      photo: null,
      house_no: "",
      email: "drew@leyyow.com",
      phone: "09039335002",
      line1: "",
      line2: "",
      city: "",
      state: "",
      date_of_birth: null,
      lifetime_orders: 1,
      is_customer: false,
      paystack_code: "",
      paystack_id: "",
      last_purchase: "2025-08-21T09:24:23.485355+01:00",
      net_spend: 10000,
      created: "2025-08-21T09:24:23.441787+01:00",
      address_code: null,
      full_address: null,
    },
    shipping_price: "0.00",
    products_total: "10000.00",
    fulfilled: 0,
    unique_items: 1,
    paid_amount: "0.00",
    shipping_company: "0",
    rate: null,
    shipping_paid: false,
    shipping_mode: false,
    payment_status: 2,
    payment_mode: 1,
    channel: 3,
    refund: false,
    refund_amount: "0.00",
    issues_count: 0,
    cancelled: false,
    address: null,
    order_date: "2025-08-21T00:00:00+01:00",
    items: [
      {
        id: 5615,
        has_feedback: false,
        index: 0,
        lead_time: 5,
        note: "",
        product: 1448,
        productid: 1448,
        sku: 2064,
        product_info: {
          id: 1448,
          product_name: "shoe",
          product_type: "",
          description: "",
          price: 10000,
          total_stock: 100,
          has_variant: false,
          display: true,
          discount: "",
          discount_type: "0",
          has_discount: false,
          slug: "drew",
          store: "drew",
          temp_id: "",
          category: null,
          rating: "0.0",
          review_count: 0,
          rate_tracking: "0,0,0,0,0",
          strict_stock_count: true,
          created: "2025-08-15T02:07:07.481219+01:00",
          last_sale: "2025-08-21T09:24:23.453579+01:00",
          options1: "",
          options2: "",
          options3: "",
          variants: "",
          combinations: null,
          images: [],
          sku: [
            {
              id: 2064,
              sku: "0afa3394-cc25-4117-bddb-e97320276fe1",
              option1: "",
              option2: "",
              option3: "",
              has_discount: false,
              sku_discount: "",
              sku_discount_type: "0",
              price: 10000,
              qty: 100,
              event_data: {
                "88": {
                  qty: 99,
                  price: 10000,
                },
              },
            },
          ],
          events: [
            {
              id: 88,
              event_ref: "ad83673777",
              event_name: "staging",
              start_date: "2025-08-15",
              end_date: "2026-01-01",
              created: "2025-08-15T02:08:25.349374+01:00",
            },
          ],
          display_event_data: {
            "88": {
              display_product: true,
            },
          },
          inventory_data: {
            "88": 100,
          },
          unit_weight: "2.000",
          length: "0.00",
          breadth: "0.00",
          height: "0.00",
        },
        var1name: "",
        var2name: "",
        selected_option1: "",
        selected_option2: "",
        qty: 1,
        delivered_qty: 0,
        price_sold: 10000,
        status: 1,
        sub_total: "10000",
        created: "2025-08-21T09:24:23.449447+01:00",
        modified: "2025-08-21T09:24:23.449478+01:00",
        selected_position: 1,
        is_returned: false,
        images: [],
      },
    ],
    event: 88,
    is_voided: false,
    void_reason: null,
    status: 0,
    shipping_provider: "manual",
    has_shipping: false,
  },
  {
    id: 3172,
    order_ref: "30225082001251573",
    items_count: 1,
    total_amount: "5000.00",
    store: 225,
    customer: 5232,
    customer_info: {
      id: 5232,
      uid: 5232,
      store: 225,
      first_name: "Daniel",
      last_name: "Obode",
      photo: null,
      house_no: "",
      email: "obodedaniel3@gmail.com",
      phone: "09039335002",
      line1: "",
      line2: "",
      city: "",
      state: "",
      date_of_birth: null,
      lifetime_orders: 3,
      is_customer: false,
      paystack_code: "",
      paystack_id: "",
      last_purchase: "2025-08-20T17:29:15.756142+01:00",
      net_spend: 110000,
      created: "2025-08-19T22:12:28.292439+01:00",
      address_code: null,
      full_address: null,
    },
    shipping_price: "0.00",
    products_total: "5000.00",
    fulfilled: 0,
    unique_items: 1,
    paid_amount: "0.00",
    shipping_company: "0",
    rate: null,
    shipping_paid: false,
    shipping_mode: false,
    payment_status: 0,
    payment_mode: 1,
    channel: 3,
    refund: false,
    refund_amount: "0.00",
    issues_count: 0,
    cancelled: false,
    address: null,
    order_date: "2025-08-20T00:00:00+01:00",
    items: [
      {
        id: 5608,
        has_feedback: false,
        index: 0,
        lead_time: 5,
        note: "",
        product: 1449,
        productid: 1449,
        sku: null,
        product_info: {
          id: 1449,
          product_name: "cap",
          product_type: "",
          description:
            "Our Castile Liquid Soap is a gentle, all-natural cleanser made from pure plant-based oils. Free from synthetic fragrances, parabens, and harsh chemicals, it’s perfect for everyday use on your hands, body, face, and even household cleaning.",
          price: 5000,
          total_stock: 100,
          has_variant: true,
          display: true,
          discount: "",
          discount_type: "0",
          has_discount: false,
          slug: "drew",
          store: "drew",
          temp_id: "",
          category: null,
          rating: "0.0",
          review_count: 0,
          rate_tracking: "0,0,0,0,0",
          strict_stock_count: true,
          created: "2025-08-15T02:07:29.543815+01:00",
          last_sale: "2025-08-28T16:45:04.781940+01:00",
          options1: "",
          options2: "",
          options3: "",
          variants: "",
          combinations: null,
          images: [],
          sku: [
            {
              id: 2116,
              sku: "4f7f73b9-bd0f-4bb0-b52a-3d33fa8eba3b",
              option1: "",
              option2: "",
              option3: "",
              has_discount: false,
              sku_discount: "",
              sku_discount_type: "0",
              price: 5000,
              qty: 100,
              event_data: {},
            },
          ],
          events: [
            {
              id: 88,
              event_ref: "ad83673777",
              event_name: "staging",
              start_date: "2025-08-15",
              end_date: "2026-01-01",
              created: "2025-08-15T02:08:25.349374+01:00",
            },
          ],
          display_event_data: {
            "88": {
              display_product: true,
            },
          },
          inventory_data: {
            "88": 100,
          },
          unit_weight: "2.000",
          length: "0.00",
          breadth: "0.00",
          height: "0.00",
        },
        var1name: "",
        var2name: "",
        selected_option1: "",
        selected_option2: "",
        qty: 1,
        delivered_qty: 0,
        price_sold: 5000,
        status: 1,
        sub_total: "5000",
        created: "2025-08-20T17:29:02.043008+01:00",
        modified: "2025-08-20T17:29:02.043031+01:00",
        selected_position: 1,
        is_returned: false,
        images: [],
      },
    ],
    event: 88,
    is_voided: false,
    void_reason: null,
    status: 0,
    shipping_provider: "manual",
    has_shipping: false,
  },
  {
    id: 3173,
    order_ref: "30225082001255291",
    items_count: 1,
    total_amount: "5000.00",
    store: 225,
    customer: 5232,
    customer_info: {
      id: 5232,
      uid: 5232,
      store: 225,
      first_name: "Daniel",
      last_name: "Obode",
      photo: null,
      house_no: "",
      email: "obodedaniel3@gmail.com",
      phone: "09039335002",
      line1: "",
      line2: "",
      city: "",
      state: "",
      date_of_birth: null,
      lifetime_orders: 3,
      is_customer: false,
      paystack_code: "",
      paystack_id: "",
      last_purchase: "2025-08-20T17:29:15.756142+01:00",
      net_spend: 110000,
      created: "2025-08-19T22:12:28.292439+01:00",
      address_code: null,
      full_address: null,
    },
    shipping_price: "0.00",
    products_total: "5000.00",
    fulfilled: 0,
    unique_items: 1,
    paid_amount: "0.00",
    shipping_company: "0",
    rate: null,
    shipping_paid: false,
    shipping_mode: false,
    payment_status: 0,
    payment_mode: 1,
    channel: 3,
    refund: false,
    refund_amount: "0.00",
    issues_count: 0,
    cancelled: false,
    address: null,
    order_date: "2025-08-20T00:00:00+01:00",
    items: [
      {
        id: 5609,
        has_feedback: false,
        index: 0,
        lead_time: 5,
        note: "",
        product: 1449,
        productid: 1449,
        sku: null,
        product_info: {
          id: 1449,
          product_name: "cap",
          product_type: "",
          description:
            "Our Castile Liquid Soap is a gentle, all-natural cleanser made from pure plant-based oils. Free from synthetic fragrances, parabens, and harsh chemicals, it’s perfect for everyday use on your hands, body, face, and even household cleaning.",
          price: 5000,
          total_stock: 100,
          has_variant: true,
          display: true,
          discount: "",
          discount_type: "0",
          has_discount: false,
          slug: "drew",
          store: "drew",
          temp_id: "",
          category: null,
          rating: "0.0",
          review_count: 0,
          rate_tracking: "0,0,0,0,0",
          strict_stock_count: true,
          created: "2025-08-15T02:07:29.543815+01:00",
          last_sale: "2025-08-28T16:45:04.781940+01:00",
          options1: "",
          options2: "",
          options3: "",
          variants: "",
          combinations: null,
          images: [],
          sku: [
            {
              id: 2116,
              sku: "4f7f73b9-bd0f-4bb0-b52a-3d33fa8eba3b",
              option1: "",
              option2: "",
              option3: "",
              has_discount: false,
              sku_discount: "",
              sku_discount_type: "0",
              price: 5000,
              qty: 100,
              event_data: {},
            },
          ],
          events: [
            {
              id: 88,
              event_ref: "ad83673777",
              event_name: "staging",
              start_date: "2025-08-15",
              end_date: "2026-01-01",
              created: "2025-08-15T02:08:25.349374+01:00",
            },
          ],
          display_event_data: {
            "88": {
              display_product: true,
            },
          },
          inventory_data: {
            "88": 100,
          },
          unit_weight: "2.000",
          length: "0.00",
          breadth: "0.00",
          height: "0.00",
        },
        var1name: "",
        var2name: "",
        selected_option1: "",
        selected_option2: "",
        qty: 1,
        delivered_qty: 0,
        price_sold: 5000,
        status: 1,
        sub_total: "5000",
        created: "2025-08-20T17:29:15.715394+01:00",
        modified: "2025-08-20T17:29:15.715423+01:00",
        selected_position: 1,
        is_returned: false,
        images: [],
      },
    ],
    event: 88,
    is_voided: false,
    void_reason: null,
    status: 0,
    shipping_provider: "manual",
    has_shipping: false,
  },
  {
    id: 3171,
    order_ref: "30225081901257487",
    items_count: 1,
    total_amount: "100000.00",
    store: 225,
    customer: 5232,
    customer_info: {
      uid: 5232,
      id: 5232,
      store: 225,
      first_name: "Daniel",
      last_name: "Obode",
      photo: null,
      house_no: "",
      email: "obodedaniel3@gmail.com",
      phone: "09039335002",
      line1: "",
      line2: "",
      city: "",
      state: "",
      date_of_birth: null,
      lifetime_orders: 3,
      is_customer: false,
      paystack_code: "",
      paystack_id: "",
      last_purchase: "2025-08-20T17:29:15.756142+01:00",
      net_spend: 110000,
      created: "2025-08-19T22:12:28.292439+01:00",
      address_code: null,
      full_address: null,
    },
    shipping_price: "0.00",
    products_total: "100000.00",
    fulfilled: 0,
    unique_items: 1,
    paid_amount: "0.00",
    shipping_company: "0",
    rate: null,
    shipping_paid: false,
    shipping_mode: false,
    payment_status: 0,
    payment_mode: 1,
    channel: 3,
    refund: false,
    refund_amount: "0.00",
    issues_count: 0,
    cancelled: false,
    address: null,
    order_date: "2025-08-19T00:00:00+01:00",
    items: [
      {
        id: 5607,
        has_feedback: false,
        index: 0,
        lead_time: 5,
        note: "",
        product: 1450,
        productid: 1450,
        sku: 2066,
        product_info: {
          id: 1450,
          product_name: "phone",
          product_type: "",
          description: "",
          price: 100000,
          total_stock: 100,
          has_variant: false,
          display: true,
          discount: "",
          discount_type: "0",
          has_discount: false,
          slug: "drew",
          store: "drew",
          temp_id: "",
          category: null,
          rating: "0.0",
          review_count: 0,
          rate_tracking: "0,0,0,0,0",
          strict_stock_count: true,
          created: "2025-08-15T02:07:48.627886+01:00",
          last_sale: "2025-08-19T22:12:28.301548+01:00",
          options1: "",
          options2: "",
          options3: "",
          variants: "",
          combinations: null,
          images: [],
          sku: [
            {
              id: 2066,
              sku: "119fd198-3ad8-4a30-8fd7-3973b27bb487",
              option1: "",
              option2: "",
              option3: "",
              has_discount: false,
              sku_discount: "",
              sku_discount_type: "0",
              price: 100000,
              qty: 100,
              event_data: {
                "88": {
                  qty: 100,
                  price: 100000,
                },
                "94": {
                  qty: 99,
                  price: 100000,
                },
              },
            },
          ],
          events: [
            {
              id: 88,
              event_ref: "ad83673777",
              event_name: "staging",
              start_date: "2025-08-15",
              end_date: "2026-01-01",
              created: "2025-08-15T02:08:25.349374+01:00",
            },
            {
              id: 94,
              event_ref: "22189d16aa",
              event_name: "reg",
              start_date: "2025-08-20",
              end_date: "2027-06-20",
              created: "2025-08-19T22:09:44.467675+01:00",
            },
          ],
          display_event_data: {
            "88": {
              display_product: true,
            },
            "94": {
              display_product: true,
            },
          },
          inventory_data: {
            "88": 100,
            "94": 100,
          },
          unit_weight: "0.500",
          length: "0.00",
          breadth: "0.00",
          height: "0.00",
        },
        var1name: "",
        var2name: "",
        selected_option1: "",
        selected_option2: "",
        qty: 1,
        delivered_qty: 0,
        price_sold: 100000,
        status: 1,
        sub_total: "100000",
        created: "2025-08-19T22:12:28.298445+01:00",
        modified: "2025-08-19T22:12:28.298466+01:00",
        selected_position: 1,
        is_returned: false,
        images: [],
      },
    ],
    event: 94,
    is_voided: false,
    void_reason: null,
    status: 0,
    shipping_provider: "manual",
    has_shipping: false,
  },
]

export const ORDER_CHANNELS: TOrderChannel[] = [
  { label: "Store/Walk-in", value: 0, icon: "Shop" },
  { label: "Instagram", value: 1, icon: "Instagram" },
  { label: "Facebook", value: 5, icon: "Facebook" },
  { label: "X", value: 6, icon: "Box1" },
  { label: "Whatsapp", value: 2, icon: "Whatsapp" },
  { label: "Website", value: 3, icon: "Global" },
  { label: "Other", value: 4, icon: "Box2" },
]

export const ORDER_SHIPPING_COMPANIES: TOrderShippingCompany[] = [
  { label: "DHL", value: 1 },
  { label: "GUO Transport", value: 2 },
  { label: "GIG", value: 3 },
  { label: "Uber", value: 4 },
  { label: "Bolt", value: 5 },
  { label: "Gokada", value: 6 },
  { label: "Other", value: 0 },
]

export const ORDER_PAYMENT_METHODS: TOrderPaymentMethod[] = [
  { label: "Cash", value: 0, icon: "Moneys" },
  { label: "POS", value: 1, icon: "CardPos" },
  { label: "Transfer", value: 2, icon: "MoneyChange" },
  { label: "Other", value: 3, icon: "WalletMoney" },
]

export const ORDER_PAYMENT_STATUS: TOrderPaymentStatus[] = [
  { label: "Paid", value: 1, icon: "card-tick", color: "success" },
  { label: "Unpaid", value: 0, icon: "card-remove", color: "error" },
  { label: "Partially paid", value: 2, icon: "card-pos", color: "primary" },
]

export const anonymousCustomer: TCustomer = {
  uid: 0.1,
  id: 0.1,
  first_name: "Unknown",
  last_name: "Anonymous",
  email: "",
  phone: "",
  total_orders: 0,
  last_order_date: "",
}

export const ORDER_COLUMNS: TableColumn<TOrder>[] = [
  { header: "Order ID", accessor: "order_ref" },
  { header: "Customer", accessor: "customer_info" },
  {
    header: "Amount",
    accessor: "total_amount",
    cell: ({ value }) => formatCurrency(Number(value)),
  },
  { header: "Order", accessor: "items_count" },
  { header: "Status", accessor: "status" },
  {
    header: "Order Date",
    accessor: "order_date",
    cell: ({ value }) => getSmartDateLabel(value as string),
  },
  { header: "Actions", accessor: "actions" },
]
