// ============================================================================
// 1:1 mock payloads transcribed from
// docs/figma/command-health-center/dashboard-desktop.png (+ mobile).
// Served by api.ts while VITE_DASHBOARD_MOCK === "true" (backend not yet shipped).
// ============================================================================
import type { IDashboardHealth, IWorklistResponse, IAwarenessRail } from "./types"

export const HEALTH_FIXTURE: IDashboardHealth = {
  vitals: [
    {
      key: "sales_today",
      label: "Sales Today",
      value: "₦86,400",
      status: "positive",
      detail: "+12% on 7-day avg",
      trendUp: true,
    },
    {
      key: "orders_today",
      label: "Orders Today",
      value: "7",
      status: "positive",
      detail: "+1 on 7-day avg",
      trendUp: true,
    },
    {
      key: "deliveries_in_flight",
      label: "Deliveries in Flight",
      value: "5",
      status: "critical",
      detail: "1 failed, needs redelivery",
    },
    {
      key: "low_stock",
      label: "Low Stock",
      value: "5 Items",
      status: "warning",
      detail: "2 products · 2 inputs",
    },
    {
      key: "nearing_expiry",
      label: "Nearing Expiry",
      value: "₦31,200",
      status: "warning",
      detail: "1 batch, 9 days left",
    },
    {
      key: "owed_to_you",
      label: "Owed to You",
      value: "₦214,000",
      status: "warning",
      detail: "₦96,500 over 30 days",
    },
  ],
}

export const WORKLIST_FIXTURE: IWorklistResponse = {
  firstName: "Adaeze",
  count: 10,
  summaryLine:
    "₦298,000 is tied up or at risk across them. The heaviest is ₦142,000 of stock stranded in a popup that ended four days ago.",
  summaryLineSecondary: null,
  tasks: [
    {
      id: "task-send-out",
      variant: "aggregate",
      title: "Send out 3 orders",
      subtitle: "Paid and unfulfilled · ₦67,500 across the three",
      tags: [{ label: "Manual Delivery", color: "error", dot: true }],
      tone: "danger",
      bulkActionLabel: null,
      rows: [
        {
          id: "so-1",
          title: "Amaka Nwosu",
          reference: "#S08C2DFE5",
          urgency: "high",
          ageLabel: "7 days",
          amountLabel: "₦214,000",
          action: "mark_sent",
          actionLabel: "Resolve",
        },
        {
          id: "so-2",
          title: "Bola Adeyemi",
          reference: "#S08C2DFE5",
          urgency: "high",
          ageLabel: "7 days",
          amountLabel: "₦12,500",
          action: "mark_sent",
          actionLabel: "Resolve",
        },
        {
          id: "so-3",
          title: "Ifeoma Okafor",
          reference: "#S08C2DFE5",
          urgency: "medium",
          ageLabel: "2 days",
          amountLabel: "₦31,000",
          action: "mark_sent",
          actionLabel: "Resolve",
        },
        {
          id: "so-4",
          title: "Amaka Nwosu",
          reference: "#S08C2DFE5",
          urgency: "medium",
          ageLabel: "2 days",
          amountLabel: "₦12,500",
          action: "mark_sent",
          actionLabel: "Resolve",
        },
        {
          id: "so-5",
          title: "Amaka Nwosu",
          reference: "#S08C2DFE5",
          urgency: "low",
          ageLabel: "Today",
          amountLabel: "₦12,500",
          action: "mark_sent",
          actionLabel: "Resolve",
        },
      ],
    },
    {
      id: "task-create-shipments",
      variant: "aggregate",
      title: "Create 2 shipments",
      subtitle: "Paid, no shipment booked · ₦45,400 across the two",
      tags: [{ label: "Shipbubble", color: "warning", dot: true }],
      tone: "warning",
      bulkActionLabel: null,
      rows: [
        {
          id: "cs-1",
          title: "Amaka Nwosu",
          reference: "#S08C2DFE5",
          urgency: "high",
          ageLabel: "7 days",
          amountLabel: "₦214,000",
          action: "create_shipment",
          actionLabel: "Create",
        },
        {
          id: "cs-2",
          title: "Bola Adeyemi",
          reference: "#S08C2DFE5",
          urgency: "high",
          ageLabel: "7 days",
          amountLabel: "₦12,500",
          action: "create_shipment",
          actionLabel: "Create",
        },
        {
          id: "cs-3",
          title: "Amaka Nwosu",
          reference: "#S08C2DFE5",
          urgency: "low",
          ageLabel: "Today",
          amountLabel: "₦12,500",
          action: "create_shipment",
          actionLabel: "Create",
        },
      ],
    },
    {
      id: "task-close-popup",
      variant: "flat",
      title: "Close the Lekki Sunday Market popup",
      subtitle: "Ended 11 Jul  •  38 units still held out of main stock",
      tags: [],
      tone: "danger",
      amountLabel: "₦142,000",
      action: "close_popup",
      actionLabel: "Close Popup",
    },
    {
      id: "task-expiring",
      variant: "flat",
      title: "Rosehip oil is expiring",
      subtitle: "Batch #B-1183  •  2.4L worth ₦31,200 spoils if unused",
      tags: [
        { label: "Expires 24 Jul", color: "warning" },
        { label: "Raw material", color: "alt" },
      ],
      tone: "warning",
      action: "discount_or_use",
      actionLabel: "Discount or Use",
    },
    {
      id: "task-redeliver",
      variant: "flat",
      title: "Redeliver to Chidinma Obi",
      subtitle: "Delivery failed 14 Jul  •  #LY-2841",
      tags: [{ label: "Shipbubble", color: "alt" }],
      tone: "danger",
      amountLabel: "₦18,500",
      // NOTE: the Figma frame labels this button "Close Popup" — treated as a
      // design copy-paste typo; corrected to "Redeliver". Flip in review if intended.
      action: "reschedule",
      actionLabel: "Redeliver",
    },
    {
      id: "task-buy-shea",
      variant: "flat",
      title: "Buy shea butter",
      subtitle: "Only 3.2kg left",
      tags: [{ label: "Raw material", color: "alt" }],
      tone: "plain",
      action: "add_stock",
      actionLabel: "Add Stock",
    },
    {
      id: "task-buy-toner",
      variant: "flat",
      title: "Buy rose water toner 100ml",
      subtitle: "Only 6pcs left",
      tags: [{ label: "Product", color: "alt" }],
      tone: "plain",
      action: "add_stock",
      actionLabel: "Add Stock",
    },
    {
      id: "task-produce-cream",
      variant: "flat",
      title: "Produce whipped body cream 250ml",
      subtitle: "Only 14ml left",
      tags: [{ label: "Product", color: "alt" }],
      tone: "plain",
      action: "start_run",
      actionLabel: "Start Run",
    },
    {
      id: "task-produce-emulsion",
      variant: "flat",
      title: "Produce base emulsion",
      subtitle: "Only 6.5L left",
      tags: [{ label: "Sub-assembly", color: "alt" }],
      tone: "plain",
      action: "start_run",
      actionLabel: "Start Run",
    },
    {
      id: "task-remind-tobi",
      variant: "flat",
      title: "Remind Tobi Adesanya to collect",
      subtitle: "Ordered 29 Jun, 16 days uncollected  •  #LY-2698",
      tags: [{ label: "Pickup", color: "alt" }],
      tone: "plain",
      action: "send_reminder",
      actionLabel: "Send Reminder",
    },
  ],
}

export const AWARENESS_RAIL_FIXTURE: IAwarenessRail = {
  receivables: {
    totalLabel: "₦214,000",
    customerCount: 6,
    items: [
      {
        customerId: "c1",
        name: "Ngozi Eze",
        ageLabel: "47 days",
        amountLabel: "₦52,000",
        aged: true,
      },
      {
        customerId: "c2",
        name: "Emeka Bassey",
        ageLabel: "38 days",
        amountLabel: "₦44,500",
        aged: true,
      },
      {
        customerId: "c3",
        name: "Funke Aluko",
        ageLabel: "12 days",
        amountLabel: "₦67,000",
        aged: false,
      },
      {
        customerId: "c4",
        name: "Sade Ojo",
        ageLabel: "8 days",
        amountLabel: "₦67,000",
        aged: false,
      },
    ],
  },
  ordersInFlight: {
    outForDelivery: 5,
    waitingToBeCollected: 2,
    deliveredToday: 3,
  },
  popups: [
    { id: "p1", name: "Ikeja Weekend", statusLabel: "ends 19 Jul", active: true },
    { id: "p2", name: "Lekki Sunday Market", statusLabel: "ended 11 Jul", active: false },
  ],
}
